version: ~> 1.0
dist: bionic
language: go
os: linux
jobs:
  include:
    - go: "1.13.x"
    - go: "1.13.x"
      os: osx
    - go: "1.12.x"
env:
  global: GO111MODULE="on"

install:
  - go get ./...
script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./... -quiet

notifications:
  email: false
